# Alpine Python Duplicity Backblaze B2 image
FROM alpine:latest
Label Description="Backblaze B2 backup docker image."
Label Version="0.1"
RUN apk update \
&& apk upgrade --available \ 
&& apk add python3 duplicity \
&& pip3 install --upgrade pip \
&& pip3 install b2 \
&& rm -rf /var/cache/apk/*
WORKDIR /backup
