# Alpine Python Duplicity Backblaze B2 image
FROM alpine:latest
Label Description="Backblaze B2 backup docker image."
Label Version="0.1"
RUN apk update \
&& apk upgrade --available \ 
&& apk add duplicity py-pip \
&& pip install --upgrade pip \
&& pip install b2 \
&& rm -rf /var/cache/apk/*
WORKDIR /backup
